import Foundation

struct ProductDisplayNameProvider {
    private static let seededProductKeys: [String: String] = [
        // Essentials
        "milk": "product.milk",
        "bread": "product.bread",
        "eggs": "product.eggs",
        "egg": "product.eggs",
        "cheese": "product.cheese",
        "butter": "product.butter",
        "yogurt": "product.yogurt",
        "water": "product.water",
        "salt": "product.salt",
        "olive oil": "product.olive_oil",

        // Produce
        "tomatoes": "product.tomatoes",
        "tomato": "product.tomatoes",
        "potatoes": "product.potatoes",
        "potato": "product.potatoes",
        "carrots": "product.carrots",
        "carrot": "product.carrots",
        "cucumber": "product.cucumber",
        "lettuce": "product.lettuce",
        "broccoli": "product.broccoli",
        "peppers": "product.peppers",
        "onions": "product.onions",
        "onion": "product.onions",
        "garlic": "product.garlic",
        "ginger": "product.ginger",
        "mushrooms": "product.mushrooms",
        "avocado": "product.avocado",
        "apples": "product.apples",
        "apple": "product.apples",
        "bananas": "product.bananas",
        "banana": "product.bananas",
        "grapes": "product.grapes",
        "orange": "product.orange",
        "lemon": "product.lemon",
        "strawberries": "product.strawberries",
        "spinach": "product.spinach",
        "zucchini": "product.zucchini",
        "eggplant": "product.eggplant",
        "peas": "product.peas",
        "corn": "product.corn",
        "celery": "product.celery",
        "leek": "product.leek",
        "cabbage": "product.cabbage",
        "cauliflower": "product.cauliflower",
        "sweet potato": "product.sweet_potato",
        "sweet potatoes": "product.sweet_potato",
        "beetroot": "product.beetroot",
        "artichoke": "product.artichoke",
        "artichokes": "product.artichoke",
        "cherry tomatoes": "product.cherry_tomatoes",
        "watermelon": "product.watermelon",
        "melon": "product.melon",
        "peach": "product.peach",
        "peaches": "product.peach",
        "pear": "product.pear",
        "pears": "product.pear",
        "mango": "product.mango",
        "pineapple": "product.pineapple",
        "cherry": "product.cherry",
        "cherries": "product.cherry",
        "blueberries": "product.blueberries",
        "raspberries": "product.raspberries",
        "pomegranate": "product.pomegranate",
        "mandarin": "product.mandarin",
        "mandarins": "product.mandarin",
        "grapefruit": "product.grapefruit",
        "apricot": "product.apricot",
        "apricots": "product.apricot",
        "plum": "product.plum",
        "plums": "product.plum",
        "fig": "product.fig",
        "figs": "product.fig",
        "dates": "product.dates",
        "kiwi": "product.kiwi",
        "coconut": "product.coconut",

        // Proteins
        "tofu": "product.tofu",
        "chicken": "product.chicken",
        "ground meat": "product.ground_meat",
        "mince": "product.ground_meat",
        "minced meat": "product.ground_meat",
        "fish": "product.fish",
        "tuna": "product.tuna",
        "bacon": "product.bacon",
        "beans": "product.beans",
        "lentils": "product.lentils",
        "nuts": "product.nuts",
        "steak": "product.steak",
        "pork": "product.pork",
        "lamb": "product.lamb",
        "sausage": "product.sausage",
        "sausages": "product.sausage",
        "ham": "product.ham",
        "salmon": "product.salmon",
        "shrimp": "product.shrimp",
        "shrimps": "product.shrimp",
        "prawns": "product.shrimp",
        "turkey": "product.turkey",
        "almonds": "product.almonds",
        "walnuts": "product.walnuts",

        // Dairy extras
        "feta": "product.feta",
        "feta cheese": "product.feta",
        "cream": "product.cream",
        "cream cheese": "product.cream_cheese",
        "sour cream": "product.sour_cream",
        "almond milk": "product.almond_milk",
        "oat milk": "product.oat_milk",

        // Pantry
        "rice": "product.rice",
        "pasta": "product.pasta",
        "flour": "product.flour",
        "sugar": "product.sugar",
        "coffee": "product.coffee",
        "tea": "product.tea",
        "cereal": "product.cereal",
        "biscuits": "product.biscuits",
        "breadsticks": "product.breadsticks",
        "honey": "product.honey",
        "jam": "product.jam",
        "tomato sauce": "product.tomato_sauce",
        "mayonnaise": "product.mayonnaise",
        "mustard": "product.mustard",
        "ketchup": "product.ketchup",
        "vinegar": "product.vinegar",
        "black pepper": "product.black_pepper",
        "pepper": "product.black_pepper",
        "oregano": "product.oregano",
        "cinnamon": "product.cinnamon",
        "tahini": "product.tahini",
        "oats": "product.oats",
        "chickpeas": "product.chickpeas",
        "peanut butter": "product.peanut_butter",
        "sunflower oil": "product.sunflower_oil",
        "baking powder": "product.baking_powder",
        "cocoa": "product.cocoa",
        "soy sauce": "product.soy_sauce",
        "breadcrumbs": "product.breadcrumbs",
        "stock": "product.stock",
        "chocolate": "product.chocolate",
        "chips": "product.chips",
        "popcorn": "product.popcorn",
        "cookies": "product.cookies",

        // Frozen
        "frozen vegetables": "product.frozen_vegetables",
        "frozen pizza": "product.frozen_pizza",
        "frozen fish": "product.frozen_fish",
        "ice cream": "product.ice_cream",
        "frozen fries": "product.frozen_fries",
        "frozen chicken": "product.frozen_chicken",

        // Drinks
        "sparkling water": "product.sparkling_water",
        "juice": "product.juice",
        "soda": "product.soda",
        "beer": "product.beer",
        "wine": "product.wine",
        "energy drink": "product.energy_drink",
        "energy drinks": "product.energy_drink",
        "frappe": "product.frappe",
        "frappé": "product.frappe",
        "espresso": "product.espresso",

        // Home care
        "dish soap": "product.dish_soap",
        "laundry detergent": "product.laundry_detergent",
        "fabric softener": "product.fabric_softener",
        "bleach": "product.bleach",
        "multi-surface cleaner": "product.multi_surface_cleaner",
        "glass cleaner": "product.glass_cleaner",
        "sponges": "product.sponges",
        "trash bags": "product.trash_bags",
        "paper towels": "product.paper_towels",
        "toilet paper": "product.toilet_paper",
        "tissues": "product.tissues",
        "hand soap": "product.hand_soap",
        "shampoo": "product.shampoo",
        "toothpaste": "product.toothpaste",
        "aluminum foil": "product.aluminum_foil",
        "baking paper": "product.baking_paper",
        "conditioner": "product.conditioner",
        "body wash": "product.body_wash",
        "shower gel": "product.body_wash",
        "deodorant": "product.deodorant",
        "sunscreen": "product.sunscreen",
        "moisturizer": "product.moisturizer",
        "cotton pads": "product.cotton_pads",
        "razors": "product.razors",

        // Bakery / More
        "croissant": "product.croissant",
        "bagel": "product.bagel",
        "waffle": "product.waffle",
        "pancakes": "product.pancakes",
        "cupcake": "product.cupcake",
        "cake": "product.cake",
        "pie": "product.pie",
        "doughnut": "product.doughnut",
        "pita": "product.pita",
        "pita bread": "product.pita",
        "tortilla": "product.tortilla",
        "tortillas": "product.tortilla",
        "baguette": "product.baguette",
        "rusks": "product.rusks",
        "toast": "product.toast"
    ]

    static func displayName(for canonicalName: String) -> String {
        let normalizedName = canonicalName.lowercased()
        guard let key = seededProductKeys[normalizedName] else { return canonicalName }
        return String(localized: String.LocalizationValue(key))
    }
}
